import { Lexend, Autour_One  } from "next/font/google";
import "./globals.css";


const autourOne = Autour_One({
  variable: "--font-autour",
  subsets: ["latin"],
  weight: '400',
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lexend.variable} ${autourOne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
